name: Industry
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish:
    name: Publish Industry Targets
    strategy:
      matrix:
        feature_set: [modern]
    runs-on:
      ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # doesnt work locally
      # - uses: ./.github/actions/hugepages
      # - uses: ./.github/actions/deps

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.FUZZ_SERVICE_ACCT_JSON_BUNDLE }}

      - uses: firedancer-io/fuzzbot-builder@main
        name: Build Solana Target
        with:
          command: apt update && apt install -y zip && pushd rust/diff-sbpf_loader && cargo build &&
           mkdir ../../artdir && popd && zip ./labs-industry-bundle.zip rust/target/debug/*.so 

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: './labs-industry-bundle.zip'
          destination: firedancer-builds.isol-clusterfuzz.appspot.com/industry-labs/industry-labs.${{ github.sha }}.zip
      # - run: gcloud storage cp ./labs-industry-bundle.zip $CF_BUCKET/industry-labs/industry-labs.${{ github.sha }}.zip