name: Industry
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish:
    name: Publish Industry Targets
    strategy:
      matrix:
        feature_set: [modern]
    runs-on:
      ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # doesnt work locally
      # - uses: ./.github/actions/hugepages
      # - uses: ./.github/actions/deps
      - run: sudo apt update && sudo apt install -y zip

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.FUZZ_SERVICE_ACCT_JSON_BUNDLE }}

      - uses: firedancer-io/fuzzbot-builder@main
        name: Build Solana Target
        with:
          command: cd firedancer && make -j -Otarget shared

      - uses: firedancer-io/clusterfuzz-action@main
        name: Upload fuzz targets to ClusterFuzz
        with:
          bucket-name: $CF_BUCKET
          artifact-dir: build/linux/clang/combi/${{ matrix.feature_set }}/fuzz-test
          object-prefix: industry-labs/
          project-id: isol-clusterfuzz
          qualifier: ${{ matrix.feature_set }}
          service-account-credentials: ${{ secrets.FUZZ_SERVICE_ACCT_JSON_BUNDLE }}

      - run: gcloud storage cp build/linux/clang/icelake/industry-bundle.zip gs://firedancer-builds.isol-clusterfuzz.appspot.com/industry-fd/industry-fd.${{ github.sha }}.zip